api_platform:
    title: crm-react
    version: 1.0.0
    formats:
        jsonld:
            mime_types: ["application/ld+json"]

        json:
            mime_types: ["application/json"]
    use_symfony_listeners: true
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
        pagination_enabled: false
        pagination_items_per_page: 25
        pagination_maximum_items_per_page: 200
